/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TakeQuizRouteImport } from './routes/take-quiz'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateQuizRouteImport } from './routes/create-quiz'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserUserIdRouteImport } from './routes/user.$userId'
import { Route as QuizQuizIdRouteImport } from './routes/quiz.$quizId'
import { Route as ApiDebugSessionRouteImport } from './routes/api/debug-session'
import { Route as QuizQuizIdTakeRouteImport } from './routes/quiz.$quizId_.take'
import { Route as QuizQuizIdEditRouteImport } from './routes/quiz.$quizId_.edit'
import { Route as ApiUserUpdatePasswordRouteImport } from './routes/api/user/update-password'
import { Route as ApiUserUpdateBioRouteImport } from './routes/api/user/update-bio'
import { Route as ApiTagsSearchRouteImport } from './routes/api/tags/search'
import { Route as ApiTagsListRouteImport } from './routes/api/tags/list'
import { Route as ApiQuizUserQuizzesRouteImport } from './routes/api/quiz/user-quizzes'
import { Route as ApiQuizPublicQuizzesRouteImport } from './routes/api/quiz/public-quizzes'
import { Route as ApiQuizCreateRouteImport } from './routes/api/quiz/create'
import { Route as ApiQuizQuizIdRouteImport } from './routes/api/quiz/$quizId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiUserUserIdProfileRouteImport } from './routes/api/user/$userId.profile'
import { Route as ApiUserUserIdBookmarksRouteImport } from './routes/api/user/$userId.bookmarks'
import { Route as ApiQuizQuizIdUpdateRouteImport } from './routes/api/quiz/$quizId.update'
import { Route as ApiQuizQuizIdTakeRouteImport } from './routes/api/quiz/$quizId.take'
import { Route as ApiQuizQuizIdSubmitRouteImport } from './routes/api/quiz/$quizId.submit'
import { Route as ApiQuizQuizIdDeleteRouteImport } from './routes/api/quiz/$quizId.delete'
import { Route as ApiQuizQuizIdBookmarkRouteImport } from './routes/api/quiz/$quizId.bookmark'

const TakeQuizRoute = TakeQuizRouteImport.update({
  id: '/take-quiz',
  path: '/take-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateQuizRoute = CreateQuizRouteImport.update({
  id: '/create-quiz',
  path: '/create-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugSessionRoute = ApiDebugSessionRouteImport.update({
  id: '/api/debug-session',
  path: '/api/debug-session',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdTakeRoute = QuizQuizIdTakeRouteImport.update({
  id: '/quiz/$quizId_/take',
  path: '/quiz/$quizId/take',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdEditRoute = QuizQuizIdEditRouteImport.update({
  id: '/quiz/$quizId_/edit',
  path: '/quiz/$quizId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserUpdatePasswordRoute = ApiUserUpdatePasswordRouteImport.update({
  id: '/api/user/update-password',
  path: '/api/user/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserUpdateBioRoute = ApiUserUpdateBioRouteImport.update({
  id: '/api/user/update-bio',
  path: '/api/user/update-bio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsSearchRoute = ApiTagsSearchRouteImport.update({
  id: '/api/tags/search',
  path: '/api/tags/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTagsListRoute = ApiTagsListRouteImport.update({
  id: '/api/tags/list',
  path: '/api/tags/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizUserQuizzesRoute = ApiQuizUserQuizzesRouteImport.update({
  id: '/api/quiz/user-quizzes',
  path: '/api/quiz/user-quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizPublicQuizzesRoute = ApiQuizPublicQuizzesRouteImport.update({
  id: '/api/quiz/public-quizzes',
  path: '/api/quiz/public-quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizCreateRoute = ApiQuizCreateRouteImport.update({
  id: '/api/quiz/create',
  path: '/api/quiz/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizQuizIdRoute = ApiQuizQuizIdRouteImport.update({
  id: '/api/quiz/$quizId',
  path: '/api/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserUserIdProfileRoute = ApiUserUserIdProfileRouteImport.update({
  id: '/api/user/$userId/profile',
  path: '/api/user/$userId/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserUserIdBookmarksRoute = ApiUserUserIdBookmarksRouteImport.update({
  id: '/api/user/$userId/bookmarks',
  path: '/api/user/$userId/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuizQuizIdUpdateRoute = ApiQuizQuizIdUpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => ApiQuizQuizIdRoute,
} as any)
const ApiQuizQuizIdTakeRoute = ApiQuizQuizIdTakeRouteImport.update({
  id: '/take',
  path: '/take',
  getParentRoute: () => ApiQuizQuizIdRoute,
} as any)
const ApiQuizQuizIdSubmitRoute = ApiQuizQuizIdSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ApiQuizQuizIdRoute,
} as any)
const ApiQuizQuizIdDeleteRoute = ApiQuizQuizIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => ApiQuizQuizIdRoute,
} as any)
const ApiQuizQuizIdBookmarkRoute = ApiQuizQuizIdBookmarkRouteImport.update({
  id: '/bookmark',
  path: '/bookmark',
  getParentRoute: () => ApiQuizQuizIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/create-quiz': typeof CreateQuizRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/take-quiz': typeof TakeQuizRoute
  '/api/debug-session': typeof ApiDebugSessionRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/quiz/$quizId': typeof ApiQuizQuizIdRouteWithChildren
  '/api/quiz/create': typeof ApiQuizCreateRoute
  '/api/quiz/public-quizzes': typeof ApiQuizPublicQuizzesRoute
  '/api/quiz/user-quizzes': typeof ApiQuizUserQuizzesRoute
  '/api/tags/list': typeof ApiTagsListRoute
  '/api/tags/search': typeof ApiTagsSearchRoute
  '/api/user/update-bio': typeof ApiUserUpdateBioRoute
  '/api/user/update-password': typeof ApiUserUpdatePasswordRoute
  '/quiz/$quizId/edit': typeof QuizQuizIdEditRoute
  '/quiz/$quizId/take': typeof QuizQuizIdTakeRoute
  '/api/quiz/$quizId/bookmark': typeof ApiQuizQuizIdBookmarkRoute
  '/api/quiz/$quizId/delete': typeof ApiQuizQuizIdDeleteRoute
  '/api/quiz/$quizId/submit': typeof ApiQuizQuizIdSubmitRoute
  '/api/quiz/$quizId/take': typeof ApiQuizQuizIdTakeRoute
  '/api/quiz/$quizId/update': typeof ApiQuizQuizIdUpdateRoute
  '/api/user/$userId/bookmarks': typeof ApiUserUserIdBookmarksRoute
  '/api/user/$userId/profile': typeof ApiUserUserIdProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/create-quiz': typeof CreateQuizRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/take-quiz': typeof TakeQuizRoute
  '/api/debug-session': typeof ApiDebugSessionRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/quiz/$quizId': typeof ApiQuizQuizIdRouteWithChildren
  '/api/quiz/create': typeof ApiQuizCreateRoute
  '/api/quiz/public-quizzes': typeof ApiQuizPublicQuizzesRoute
  '/api/quiz/user-quizzes': typeof ApiQuizUserQuizzesRoute
  '/api/tags/list': typeof ApiTagsListRoute
  '/api/tags/search': typeof ApiTagsSearchRoute
  '/api/user/update-bio': typeof ApiUserUpdateBioRoute
  '/api/user/update-password': typeof ApiUserUpdatePasswordRoute
  '/quiz/$quizId/edit': typeof QuizQuizIdEditRoute
  '/quiz/$quizId/take': typeof QuizQuizIdTakeRoute
  '/api/quiz/$quizId/bookmark': typeof ApiQuizQuizIdBookmarkRoute
  '/api/quiz/$quizId/delete': typeof ApiQuizQuizIdDeleteRoute
  '/api/quiz/$quizId/submit': typeof ApiQuizQuizIdSubmitRoute
  '/api/quiz/$quizId/take': typeof ApiQuizQuizIdTakeRoute
  '/api/quiz/$quizId/update': typeof ApiQuizQuizIdUpdateRoute
  '/api/user/$userId/bookmarks': typeof ApiUserUserIdBookmarksRoute
  '/api/user/$userId/profile': typeof ApiUserUserIdProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/create-quiz': typeof CreateQuizRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/take-quiz': typeof TakeQuizRoute
  '/api/debug-session': typeof ApiDebugSessionRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/quiz/$quizId': typeof ApiQuizQuizIdRouteWithChildren
  '/api/quiz/create': typeof ApiQuizCreateRoute
  '/api/quiz/public-quizzes': typeof ApiQuizPublicQuizzesRoute
  '/api/quiz/user-quizzes': typeof ApiQuizUserQuizzesRoute
  '/api/tags/list': typeof ApiTagsListRoute
  '/api/tags/search': typeof ApiTagsSearchRoute
  '/api/user/update-bio': typeof ApiUserUpdateBioRoute
  '/api/user/update-password': typeof ApiUserUpdatePasswordRoute
  '/quiz/$quizId_/edit': typeof QuizQuizIdEditRoute
  '/quiz/$quizId_/take': typeof QuizQuizIdTakeRoute
  '/api/quiz/$quizId/bookmark': typeof ApiQuizQuizIdBookmarkRoute
  '/api/quiz/$quizId/delete': typeof ApiQuizQuizIdDeleteRoute
  '/api/quiz/$quizId/submit': typeof ApiQuizQuizIdSubmitRoute
  '/api/quiz/$quizId/take': typeof ApiQuizQuizIdTakeRoute
  '/api/quiz/$quizId/update': typeof ApiQuizQuizIdUpdateRoute
  '/api/user/$userId/bookmarks': typeof ApiUserUserIdBookmarksRoute
  '/api/user/$userId/profile': typeof ApiUserUserIdProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/create-quiz'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/take-quiz'
    | '/api/debug-session'
    | '/quiz/$quizId'
    | '/user/$userId'
    | '/api/auth/$'
    | '/api/quiz/$quizId'
    | '/api/quiz/create'
    | '/api/quiz/public-quizzes'
    | '/api/quiz/user-quizzes'
    | '/api/tags/list'
    | '/api/tags/search'
    | '/api/user/update-bio'
    | '/api/user/update-password'
    | '/quiz/$quizId/edit'
    | '/quiz/$quizId/take'
    | '/api/quiz/$quizId/bookmark'
    | '/api/quiz/$quizId/delete'
    | '/api/quiz/$quizId/submit'
    | '/api/quiz/$quizId/take'
    | '/api/quiz/$quizId/update'
    | '/api/user/$userId/bookmarks'
    | '/api/user/$userId/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/create-quiz'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/take-quiz'
    | '/api/debug-session'
    | '/quiz/$quizId'
    | '/user/$userId'
    | '/api/auth/$'
    | '/api/quiz/$quizId'
    | '/api/quiz/create'
    | '/api/quiz/public-quizzes'
    | '/api/quiz/user-quizzes'
    | '/api/tags/list'
    | '/api/tags/search'
    | '/api/user/update-bio'
    | '/api/user/update-password'
    | '/quiz/$quizId/edit'
    | '/quiz/$quizId/take'
    | '/api/quiz/$quizId/bookmark'
    | '/api/quiz/$quizId/delete'
    | '/api/quiz/$quizId/submit'
    | '/api/quiz/$quizId/take'
    | '/api/quiz/$quizId/update'
    | '/api/user/$userId/bookmarks'
    | '/api/user/$userId/profile'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/create-quiz'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/take-quiz'
    | '/api/debug-session'
    | '/quiz/$quizId'
    | '/user/$userId'
    | '/api/auth/$'
    | '/api/quiz/$quizId'
    | '/api/quiz/create'
    | '/api/quiz/public-quizzes'
    | '/api/quiz/user-quizzes'
    | '/api/tags/list'
    | '/api/tags/search'
    | '/api/user/update-bio'
    | '/api/user/update-password'
    | '/quiz/$quizId_/edit'
    | '/quiz/$quizId_/take'
    | '/api/quiz/$quizId/bookmark'
    | '/api/quiz/$quizId/delete'
    | '/api/quiz/$quizId/submit'
    | '/api/quiz/$quizId/take'
    | '/api/quiz/$quizId/update'
    | '/api/user/$userId/bookmarks'
    | '/api/user/$userId/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CreateQuizRoute: typeof CreateQuizRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TakeQuizRoute: typeof TakeQuizRoute
  ApiDebugSessionRoute: typeof ApiDebugSessionRoute
  QuizQuizIdRoute: typeof QuizQuizIdRoute
  UserUserIdRoute: typeof UserUserIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiQuizQuizIdRoute: typeof ApiQuizQuizIdRouteWithChildren
  ApiQuizCreateRoute: typeof ApiQuizCreateRoute
  ApiQuizPublicQuizzesRoute: typeof ApiQuizPublicQuizzesRoute
  ApiQuizUserQuizzesRoute: typeof ApiQuizUserQuizzesRoute
  ApiTagsListRoute: typeof ApiTagsListRoute
  ApiTagsSearchRoute: typeof ApiTagsSearchRoute
  ApiUserUpdateBioRoute: typeof ApiUserUpdateBioRoute
  ApiUserUpdatePasswordRoute: typeof ApiUserUpdatePasswordRoute
  QuizQuizIdEditRoute: typeof QuizQuizIdEditRoute
  QuizQuizIdTakeRoute: typeof QuizQuizIdTakeRoute
  ApiUserUserIdBookmarksRoute: typeof ApiUserUserIdBookmarksRoute
  ApiUserUserIdProfileRoute: typeof ApiUserUserIdProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/take-quiz': {
      id: '/take-quiz'
      path: '/take-quiz'
      fullPath: '/take-quiz'
      preLoaderRoute: typeof TakeQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-quiz': {
      id: '/create-quiz'
      path: '/create-quiz'
      fullPath: '/create-quiz'
      preLoaderRoute: typeof CreateQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-session': {
      id: '/api/debug-session'
      path: '/api/debug-session'
      fullPath: '/api/debug-session'
      preLoaderRoute: typeof ApiDebugSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId_/take': {
      id: '/quiz/$quizId_/take'
      path: '/quiz/$quizId/take'
      fullPath: '/quiz/$quizId/take'
      preLoaderRoute: typeof QuizQuizIdTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId_/edit': {
      id: '/quiz/$quizId_/edit'
      path: '/quiz/$quizId/edit'
      fullPath: '/quiz/$quizId/edit'
      preLoaderRoute: typeof QuizQuizIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/update-password': {
      id: '/api/user/update-password'
      path: '/api/user/update-password'
      fullPath: '/api/user/update-password'
      preLoaderRoute: typeof ApiUserUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/update-bio': {
      id: '/api/user/update-bio'
      path: '/api/user/update-bio'
      fullPath: '/api/user/update-bio'
      preLoaderRoute: typeof ApiUserUpdateBioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags/search': {
      id: '/api/tags/search'
      path: '/api/tags/search'
      fullPath: '/api/tags/search'
      preLoaderRoute: typeof ApiTagsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tags/list': {
      id: '/api/tags/list'
      path: '/api/tags/list'
      fullPath: '/api/tags/list'
      preLoaderRoute: typeof ApiTagsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quiz/user-quizzes': {
      id: '/api/quiz/user-quizzes'
      path: '/api/quiz/user-quizzes'
      fullPath: '/api/quiz/user-quizzes'
      preLoaderRoute: typeof ApiQuizUserQuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quiz/public-quizzes': {
      id: '/api/quiz/public-quizzes'
      path: '/api/quiz/public-quizzes'
      fullPath: '/api/quiz/public-quizzes'
      preLoaderRoute: typeof ApiQuizPublicQuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quiz/create': {
      id: '/api/quiz/create'
      path: '/api/quiz/create'
      fullPath: '/api/quiz/create'
      preLoaderRoute: typeof ApiQuizCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quiz/$quizId': {
      id: '/api/quiz/$quizId'
      path: '/api/quiz/$quizId'
      fullPath: '/api/quiz/$quizId'
      preLoaderRoute: typeof ApiQuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/$userId/profile': {
      id: '/api/user/$userId/profile'
      path: '/api/user/$userId/profile'
      fullPath: '/api/user/$userId/profile'
      preLoaderRoute: typeof ApiUserUserIdProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/$userId/bookmarks': {
      id: '/api/user/$userId/bookmarks'
      path: '/api/user/$userId/bookmarks'
      fullPath: '/api/user/$userId/bookmarks'
      preLoaderRoute: typeof ApiUserUserIdBookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quiz/$quizId/update': {
      id: '/api/quiz/$quizId/update'
      path: '/update'
      fullPath: '/api/quiz/$quizId/update'
      preLoaderRoute: typeof ApiQuizQuizIdUpdateRouteImport
      parentRoute: typeof ApiQuizQuizIdRoute
    }
    '/api/quiz/$quizId/take': {
      id: '/api/quiz/$quizId/take'
      path: '/take'
      fullPath: '/api/quiz/$quizId/take'
      preLoaderRoute: typeof ApiQuizQuizIdTakeRouteImport
      parentRoute: typeof ApiQuizQuizIdRoute
    }
    '/api/quiz/$quizId/submit': {
      id: '/api/quiz/$quizId/submit'
      path: '/submit'
      fullPath: '/api/quiz/$quizId/submit'
      preLoaderRoute: typeof ApiQuizQuizIdSubmitRouteImport
      parentRoute: typeof ApiQuizQuizIdRoute
    }
    '/api/quiz/$quizId/delete': {
      id: '/api/quiz/$quizId/delete'
      path: '/delete'
      fullPath: '/api/quiz/$quizId/delete'
      preLoaderRoute: typeof ApiQuizQuizIdDeleteRouteImport
      parentRoute: typeof ApiQuizQuizIdRoute
    }
    '/api/quiz/$quizId/bookmark': {
      id: '/api/quiz/$quizId/bookmark'
      path: '/bookmark'
      fullPath: '/api/quiz/$quizId/bookmark'
      preLoaderRoute: typeof ApiQuizQuizIdBookmarkRouteImport
      parentRoute: typeof ApiQuizQuizIdRoute
    }
  }
}

interface ApiQuizQuizIdRouteChildren {
  ApiQuizQuizIdBookmarkRoute: typeof ApiQuizQuizIdBookmarkRoute
  ApiQuizQuizIdDeleteRoute: typeof ApiQuizQuizIdDeleteRoute
  ApiQuizQuizIdSubmitRoute: typeof ApiQuizQuizIdSubmitRoute
  ApiQuizQuizIdTakeRoute: typeof ApiQuizQuizIdTakeRoute
  ApiQuizQuizIdUpdateRoute: typeof ApiQuizQuizIdUpdateRoute
}

const ApiQuizQuizIdRouteChildren: ApiQuizQuizIdRouteChildren = {
  ApiQuizQuizIdBookmarkRoute: ApiQuizQuizIdBookmarkRoute,
  ApiQuizQuizIdDeleteRoute: ApiQuizQuizIdDeleteRoute,
  ApiQuizQuizIdSubmitRoute: ApiQuizQuizIdSubmitRoute,
  ApiQuizQuizIdTakeRoute: ApiQuizQuizIdTakeRoute,
  ApiQuizQuizIdUpdateRoute: ApiQuizQuizIdUpdateRoute,
}

const ApiQuizQuizIdRouteWithChildren = ApiQuizQuizIdRoute._addFileChildren(
  ApiQuizQuizIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CreateQuizRoute: CreateQuizRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TakeQuizRoute: TakeQuizRoute,
  ApiDebugSessionRoute: ApiDebugSessionRoute,
  QuizQuizIdRoute: QuizQuizIdRoute,
  UserUserIdRoute: UserUserIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiQuizQuizIdRoute: ApiQuizQuizIdRouteWithChildren,
  ApiQuizCreateRoute: ApiQuizCreateRoute,
  ApiQuizPublicQuizzesRoute: ApiQuizPublicQuizzesRoute,
  ApiQuizUserQuizzesRoute: ApiQuizUserQuizzesRoute,
  ApiTagsListRoute: ApiTagsListRoute,
  ApiTagsSearchRoute: ApiTagsSearchRoute,
  ApiUserUpdateBioRoute: ApiUserUpdateBioRoute,
  ApiUserUpdatePasswordRoute: ApiUserUpdatePasswordRoute,
  QuizQuizIdEditRoute: QuizQuizIdEditRoute,
  QuizQuizIdTakeRoute: QuizQuizIdTakeRoute,
  ApiUserUserIdBookmarksRoute: ApiUserUserIdBookmarksRoute,
  ApiUserUserIdProfileRoute: ApiUserUserIdProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
